### PR TITLE
[stable/openebs]: update helm chart to 2.10.0

### PR DESCRIPTION
**Pull request by akhilerm**
- update chart version
- update values
- update README
- update dependency charts
- fix indentation in webhook cleanup template

Signed-off-by: Akhil Mohan <akhil.mohan@mayadata.io>

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/openebs]`)

### CODE REVIEW

**Review by shovanmaity — COMMENTED** [review]
do you want to send another pr to update dependency chart version?

**Comment by akhilerm** [comment]
> do you want to send another pr to update dependency chart version?

Nope, Will do it in the same PR. Thought I will update it only once the charts are available.

Also e2e uses the helm chart from this PR during helm update testing. cc: @nsathyaseelan

**Comment by akhilerm** [comment]
@shovanmaity Updated the dependency charts in the PR.

**Comment by shovanmaity** [comment]
Hi @akhilerm  can you please include this patch in this PR?

[0001-fix-helm-chart-fix-indentation-issue-for-webhook-cle.txt](https://github.com/openebs/charts/files/6652814/0001-fix-helm-chart-fix-indentation-issue-for-webhook-cle.txt)

ref - 
https://github.com/openebs/charts/pull/225#discussion_r651406055
https://github.com/openebs/charts/pull/225#discussion_r651406260

**Comment by akhilerm** [comment]
Done @shovanmaity

**Comment by shovanmaity** [comment]
> Done @shovanmaity

Thank you!

**Review by shovanmaity — APPROVED** [review]
/lgtm

**Review by prateekpandey14 — APPROVED** [review]
looks good

**Pull request merged**
