### PR TITLE
chore(operator): add openebs operator 2.5.0

### PR DESCRIPTION
**Pull request by akhilerm**
- add openebs operator 2.5.0 (RC1, RC2)
- add cstor operator 2.5.0 (RC1, RC2)
- add zfs operator 1.3.0 (RC1, RC2)
- add ndm operator 1.1.0 (RC1, RC2)
- delete openebs operator arm and ppc64le versions in favour of the multiarch operator

**Special notes to reviwer**
arm and ppc operator files are removed. Links pointing to those files also should be updated

Signed-off-by: Akhil Mohan <akhil.mohan@mayadata.io>

### CODE REVIEW

**Comment by prateekpandey14** [comment]
@akhilerm refer this PR for the cstor-operator specific new changes : https://github.com/openebs/cstor-operators/pull/218

**Comment by prateekpandey14** [comment]
CStor-operators changes are good

**Comment by akhilerm** [comment]
> CStor-operators changes are good

@prateek14 Should the snapshot class related resources also be added?

**Comment by akhilerm** [comment]
@prateekpandey14 @pawanpraka1 @shubham14bajpai  RC2 changes have been added. cc: @nsathyaseelan

**Review by kmova — APPROVED** [review]

**Comment by pawanpraka1** [comment]
@akhilerm can raise a PR to update the zfs-operator yaml? Sorry I couldn't review this. We have updated the k8s CRD versions to v1 and also started using new csi images in 1.3.

**Pull request merged**
